# Generated by Django 4.1.3 on 2022-11-22 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_journal_pupil_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='pupils',
            new_name='pupil',
        ),
    ]
