# Generated by Django 4.1.3 on 2022-11-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_pupils_journal_pupil'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journal',
            old_name='pupil_class',
            new_name='pupils_class',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='teachers_clas',
            new_name='teachers_class',
        ),
        migrations.RenameField(
            model_name='teachers',
            old_name='teaching_lesson',
            new_name='teachers_lesson',
        ),
    ]
