# Generated by Django 4.1.3 on 2022-11-23 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_pupil_class_journal_pupils_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupils',
            name='current_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.classes'),
        ),
    ]
